
FIND_LIBRARY(LIBGCC_LIBRARY NAMES gcc)

IF (LIBGCC_LIBRARY)
  SET(LIBGCC_FOUND TRUE)
ENDIF (LIBGCC_LIBRARY)


IF (LIBGCC_FOUND)
  IF (NOT LIBGCC_FIND_QUIETLY)
    MESSAGE(STATUS "Found libgcc: ${LIBGCC_LIBRARY}")
  ENDIF (NOT LIBGCC_FIND_QUIETLY)
ELSE (LIBGCC_FOUND)
  IF (LIBGCC_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find libgcc")
  ENDIF (LIBGCC_FIND_REQUIRED)
ENDIF (LIBGCC_FOUND)
