FIND_PATH(BARVINOK_INCLUDE_DIR barvinok/barvinok.h)

FIND_LIBRARY(BARVINOK_LIBRARY NAMES barvinok)

IF (BARVINOK_INCLUDE_DIR AND BARVINOK_LIBRARY)
  SET(BARVINOK_FOUND TRUE)
ENDIF (BARVINOK_INCLUDE_DIR AND BARVINOK_LIBRARY)


IF (BARVINOK_FOUND)
  IF (NOT BARVINOK_FIND_QUIETLY)
    MESSAGE(STATUS "Found Barvinok: ${BARVINOK_LIBRARY}")
  ENDIF (NOT BARVINOK_FIND_QUIETLY)
ELSE (BARVINOK_FOUND)
  IF (BARVINOK_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find Barvinok")
  ENDIF (BARVINOK_FIND_REQUIRED)
ENDIF (BARVINOK_FOUND)
