FIND_PATH(POLYLIB_INCLUDE_DIR barvinok/polylib.h)

FIND_LIBRARY(POLYLIB_LIBRARY NAMES polylib)

IF (POLYLIB_LIBRARY)
  SET(POLYLIB_FOUND TRUE)
ENDIF (POLYLIB_LIBRARY)


IF (POLYLIB_FOUND)
  IF (NOT POLYLIB_FIND_QUIETLY)
    MESSAGE(STATUS "Found polylib: ${POLYLIB_LIBRARY}")
  ENDIF (NOT POLYLIB_FIND_QUIETLY)
ELSE (POLYLIB_FOUND)
  IF (POLYLIB_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find polylib")
  ENDIF (POLYLIB_FIND_REQUIRED)
ENDIF (POLYLIB_FOUND)
