FIND_PATH(NTL_INCLUDE_DIR NTL/mat_ZZ.h)

FIND_LIBRARY(NTL_LIBRARY NAMES ntl)

IF (NTL_LIBRARY)
  SET(NTL_FOUND TRUE)
ENDIF (NTL_LIBRARY)


IF (NTL_FOUND)
  IF (NOT NTL_FIND_QUIETLY)
    MESSAGE(STATUS "Found NTL: ${NTL_LIBRARY}")
  ENDIF (NOT NTL_FIND_QUIETLY)
ELSE (NTL_FOUND)
  IF (NTL_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find NTL")
  ENDIF (NTL_FIND_REQUIRED)
ENDIF (NTL_FOUND)
